sudo: required
services:
- docker
language: python
python:
- '2.7'
script:
- docker build -t recast/wflowserver:git-"$TRAVIS_BRANCH" .
- docker login -u $DOCKERLOGIN -p $(echo $DOCKERPW|base64 -d)
- docker push recast/wflowserver:git-"$TRAVIS_BRANCH"
env:
  global:
  - secure: iD4ruMiVZ6+5QHxmSDD4UIRvAdsJIrQnc2AFeHYCQjWIB000jh6QlOABaUyVKpvm6hdFfjPviggxN+71RQu4wJ15H8t4zIJZzEMxAnwm3utntekfWmOsrhFT0ixAXnRRWbMsfn5EcfjKNRKGeoFd1lDDKR2t14yriWd9db2cQWx0ibKT6z69lsAFJ83yUiIq6kPU0fsJcOA2yW6HRTly+lWgNvEO1t3nj0pOSeO00XzZ7Jo+jMpCQY1l3twpzsTsx/Y2oDY38+e1DPldkHU69iE6SRbn9+TzrOU3Mj4jaKz8RxxWO/B0RkiaifsR0QLUf8GLskVRpkl9GpFTYxyz2QDjgjuqCmlfzlvEEudJTUX39c7pqD0eFIDQGakMh7KaPJmprF8AdKd9192CnU5Yr2VcuaBgEf716D1CD+oyF0GqkGgi07wJqp3ZOgX0e319/qAQBuHSCRutdziky6qYo3rJDK1nn767ZMEVqpbWd5Q6ZQ+DrGNoezFkHsoWLd4+B6WU3ChmHeb1mVQR/X4gkpegQ33g5nxyb2ecB10Zp98diMbQrqjmxRumruEvCX9LSBK3ToNEIyv/VWSfacs4HpQ2g7pahsViIWOyTFU3apVj4qlE4sZwbMBdIrAbxSnMnwZ+dXsIjm5C2JQD4o3mnY7sCfxNTViEhe37U5iJBgc=
  - secure: R9lC5ZtuFlCydx5KIkajbWfLeHTIN+BhreEr2ZiCF8Wbji9TfEP4ofrOKX1BonoGFzdymJRQmA1whOVQLeTMWztySV2uUeNK9iEKNVPt/CCeGMS5o6y7kXudzvE9U50QKgLTEWv1A94uKW7u3nkm91Iykpxc2iqm//elZ6Y0tDU/mdPpevENFnfPxVEfx9PxvdO32LaGeCgmafz+4jONAAlU9faz9NIR7dW9DvFLjFiQ7xkjN9CzKRlX0laEQlufInQAxzLJ23R1UNVEkzlgybdX1Tj8M4CKXMmuIZ6dznlQWmjbeHLnyYd96ru51OukcjXhIc0NLbhqjkV4UABpe2rvd3WoWvfOlazTR4Vl6SFUSbYEniRFwzNegXiHzVDgDUBdym5zcjEm7NO6dHziWJgtXu/9olF8+v1zNuhduPdtsxCqobOzuAl3PG1ymRAd2GJsA3/afEszsc1hXePslm2efqNloEkKu1TqLdsOzAOOZIec1ZZ/MF5PKRrif977yBjEMWPySbtkaIKoR8yjFit5H6tssUf7D77cne/lFpuRTgNFPoc1ZWR5UIKAnJkAoPuXX5OM+nYtgDihAsfvbOmTan+sLymCAfYVkR+FutmInQq6qG3ufr6Wn11/vEjKhPBZQbsX585FvIEtGR0zpTOo3cSRu6CUV8Lx3BOrm+g=
